#!/usr/bin/env ruby

require_relative 'git_utils.rb'

%w[master clean].each{|branch| exit_if_on_the_branch branch}

run_git_command 'add -A'
run_git_command 'commit -m "Committing"'
checkout('codekata')

